version: '3.5'

services:
  db:
    image: postgres
    networks:
      - applications
    restart: always
    environment:
      - POSTGRES_USER=wordsbackend
      - POSTGRES_PASSWORD=wordsbackend
      - POSTGRES_DB=wordsbackend
  web:
    build: .
    networks:
      - applications
    command: sh ./entrypoint.sh
    volumes:
      - .:/opt/wordsbackend
    environment:
      - VIRTUAL_HOST=words.estegosaurios.com
    expose:
      - "8000"
    depends_on:
      - db

networks:
  applications:
    name: applications
    driver: bridge
